local luaclang = require "luaclang"

describe("parser object creation", function() 
        it("succeeds in creating object for an available file", function()
                local parser = luaclang.newParser("spec/empty.c")
                assert.are.same('userdata', type(parser))
        end)

        it("fails to create an object for an unavailable file", function()
                assert.has.errors(function()
                        luaclang.newParser("non_existent.c")
                end, "file doesn't exist")
        end)
end)

describe("cursor creation", function() 
        it("succeeds in creating translation unit cursor", function() 
                local parser = luaclang.newParser("spec/empty.c")
                local cursor = parser:getCursor()
                assert.are.same('userdata', type(cursor))
        end)       
end)

describe("cursor spelling", function() 
        it("succeeds in matching the expected output", function()
                local parser = luaclang.newParser("spec/empty.c")
                local cursor = parser:getCursor()
                local cursor_spelling = cursor:getSpelling()
                assert.are.equals(cursor_spelling, "spec/empty.c")
        end)
end)

describe("parser object disposal", function()
        it("fails when a disposed parser object is used for cursor creation", function()
                local parser = luaclang.newParser("spec/empty.c")
                parser:dispose()
                assert.has.errors(function()
                        local cursor = parser:getCursor()
                end, "calling 'getCursor' on bad self (parser object was disposed)")
        end)
        
        it("succeeds in getting the spelling of ", function()
                local parser = luaclang.newParser("spec/empty.c")
                local cursor = parser:getCursor()
                parser:dispose()
                assert.has_no.errors(function()
                        local cursor_spelling = cursor:getSpelling()
                end)
        end)

end)
